### ISSUE TITLE
代码冗余

### ISSUE THREAD

**Issue by shuijinliuxi** [shevakuilin/SKArchCutter#1]
除了 UIImageView，其他的 UIView、UIButton、UILabel 的实现都是一样的，完全可以将这些方法作为分类，在 UIView 里实现一次就可以了。

**Comment by shevakuilin** [comment]
首先十分感谢你的热心关注，这个提议我之前考虑过，是否将UIView、UIButton和UILabel的处理统一到一个方法里，在发布第一版的时候，我尝试在传入对象的类别判断后对这三个类别做一个统一处理，但是过程不太顺利，如果对渲染前的对象不做具体的类别确定，就拿不到它的layer，如果将类别在传入前就确定好，那么对这个统一处理的方法名又提出了一个要求，看起来不太优雅，我是这么考虑的，决定在下一版的时候对这里进行一个改进。再次对你的关注表示感谢！

**Comment by shuijinliuxi** [comment]
UIButton、UILabel 都是 继续自 UIView，直接实现 UIView 就可以了。

**Comment by shevakuilin** [comment]
bingo，我忽略了这个，十分感谢！
