### ISSUE TITLE
对 UILabel 设置圆角的 bug

### ISSUE THREAD

**Issue by srv7** [shevakuilin/SKArchCutter#2]
![wx20170421-181505](https://cloud.githubusercontent.com/assets/15240872/25273463/7b6426fe-26be-11e7-8ba1-074ae1015e8e.png)
对 UILabel 设置圆角时 ，结果是一个圆角 UIImageView 加在了 label 视图上
```
// Masonry 添加约束后设置的圆角
[SKArchCutter cuttingView:self.label cuttingDirection:UIRectCornerAllCorners cornerRadii:10 borderWidth:0 borderColor:[UIColor clearColor] backgroundColor:[UIColor redColor]];
```
```
- (UILabel *)label {
    if (!_label) {
        _label = [[UILabel alloc] init];
        _label.numberOfLines = 0;
    }
    return _label;
}
```

**Comment by shevakuilin** [comment]
抱歉现在才回复你，这段时间比较忙。
这个原因是由于你的label没有一个初始的frame导致的，这个工具的原理是使用绘制圆角，生成一个UIImageView来插入到你的label的图层中来达到系统圆角的效果，你的label需要有一个frame值，请确认Masonry中是否正确设置了label的size

**Comment by shevakuilin** [comment]
我的建议是，如果你决定使用Masonry进行布局，就不要使用懒加载这种方式，可以尝试:UILable * label = [UILable new];

**Comment by srv7** [comment]
这和`懒加载`没有关系，在`label`的`Maonsy`的约束中也无需指定`size`
```
        [self.label mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.mas_equalTo(self.contentView.mas_top).offset(10);
            make.left.mas_equalTo(self.contentView.mas_left).offset(15);
            make.right.mas_equalTo(self.contentView.mas_right).offset(-15);
            make.bottom.mas_equalTo(self.contentView.mas_bottom).offset(-10);
//            make.size.mas_equalTo(CGSizeMake([UIScreen mainScreen].bounds.size.width, 100));
        }];
```
```
- (UILabel *)label {
    if (!_label) {
        _label = [[UILabel alloc] init];
        _label.numberOfLines = 0;

    }
    return _label;
}
```
这样写是可以正确生成符合`label``bounds`大小的`imageView`

当`label`文字为纯中文或中英文混合的时候，`insert` 的`imageView`在文字下方，当是纯英文的时候`insert`的`imageView`在文字上方，遮挡了文字。
此外，这种设置圆角的方法在复用的`cell`中文字长度不一的`label`上不适用

**Comment by shevakuilin** [comment]
我确信在自适应高度的cell中是适用的，我已经应用于工作中，效果很理想。如果你在应用中出现不适，请让我看一下你的适用方式。中英文显示不同这个问题我会去留意查看究竟是什么地方造成的影响

**Comment by srv7** [comment]
我这里简单仿照在我实际应用场景写了一个 Demo，请看一下是哪里的问题。[git@github.com:srv7/example.git](git@github.com:srv7/example.git)  😊

**Comment by shevakuilin** [comment]
最近这么多实在太忙了，我一定抽时间看这个问题

**Comment by shevakuilin** [comment]
十分抱歉隔了这么久才来回复这个问题，这个问题是由于没有进行图片缓存而导致的，这个版本尚未来得及加上缓存机制，我会尽快补上
