### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by dourgulf** [shevakuilin/SKArchCutter#3]
1. + (void)cuttingImageView:(UIImageView *)imageView和+ (void)cuttingView:(UIView *)view的两个方法分别使用了不同的绘制圆角的方法，这是为什么呢？
2. if ([image isKindOfClass:[UIImage class]]) 这个判断是什么情况下会是NO？我觉得应该是if (image != nil)的判断才对，不知道您是怎么考虑的？
3. 判定没有初始化frame的逻辑感觉不是很精准。

**Comment by shevakuilin** [comment]
1.
这个圆角切割的基本原理是用一个“经过绘制切割后的image”，来代替本身系统的圆角。而UIView、UIButton等控件在生产中的应用一般是纯色的，所以我们可以直接使用一个UIImageView来插入UIView的视图底层，来达到圆角的效果。而直接的UIImageView不能这样做的一个原因是，考虑到UIImageView其本身可能就承载有图片，担心引起不必要的冲突
2.当image不是UIImage的时候为NO，判断image != nil只是判断是否为空，不能知道他是否属于UIImage类
3.这个问题处理的确实不太理想，这个工具还在完善中

感谢你的来信

**Comment by dourgulf** [comment]
1. 第一个问题你解析的那部分我理解了，我不理解的是为何针对UIView绘制Image的时候不适用“UIBezierPath * path = [UIBezierPath bezierPathWithRoundedRect:rect byRoundingCorners:direction cornerRadii:CGSizeMake(cornerRadii - borderWidth, cornerRadii - borderWidth)];”？
2. 你的解析只是解析了代码的含义，没有解析代码的动机。我的疑问是：
image = UIGraphicsGetImageFromCurrentImageContext();
这个方法明确告知“Returns an image based on the contents of the current bitmap-based graphics context.
You should call this function only when a bitmap-based graphics context is the current graphics context. If the current context is nil or was not created by a call to UIGraphicsBeginImageContext, this function returns nil.” 
也就是说它要么返回一个UIImage对象，要么返回nil，怎么会返回不是nil并且不是UIImage对象的情况呢？

**Comment by shevakuilin** [comment]
1.你可以这么理解，当传入的是UIImageView的时候，使用贝塞尔曲线直接截取本身图片即可，而UIView本身没有图片，我们就主动“制造”一个图片

2.我没有明确测试过是否可能存在某种特殊情况而导致返回其他类型的值，处于保守的书写习惯，我选择这么写，如果是nil，当然也不会是UIImage了

2017-04-27 18:38 GMT+08:00 dourgulf <notifications@github.com>:

**Comment by dourgulf** [comment]
懂了，多谢指教！

**Comment by shevakuilin** [comment]
与你共勉

2017-04-27 19:06 GMT+08:00 dourgulf <notifications@github.com>:
