### ISSUE TITLE
cuttingDirection：UIRectCornerTopLeft | UIRectCornerBottomRight变形问题

### ISSUE THREAD

**Issue by qianhaichao** [shevakuilin/SKArchCutter#5]

**Comment by shevakuilin** [comment]
问题可否具体描述？

**Comment by qianhaichao** [comment]
[self.addBankCardBtn mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.offset(38);
        make.right.offset(-38);
        make.top.offset(12);
        make.bottom.offset(-12);
    }];
    
    [LJNArchCutter cuttingView:self.addBankCardBtn cuttingDirection: UIRectCornerTopLeft | UIRectCornerBottomRight   cornerRadii:10 borderWidth:0 borderColor:[UIColor clearColor] backgroundColor:kHex(0xF5F5F5)];


![Snip20190820_7](https://user-images.githubusercontent.com/8566923/63310952-2e596300-c32f-11e9-9b14-18248d9cab0d.png)

**Comment by shevakuilin** [comment]
感谢反馈，会尽快修复，临时解决方案：


```objc
[self.addBankCardBtn mas_makeConstraints:^(MASConstraintMaker *make) {
/// - Note: 暂时移除左右边距设置
// make.left.offset(38);
// make.right.offset(-38);
make.top.offset(12);
make.bottom.offset(-12);
/// - Note: 设置width，宽度可根据两边距计算得出
make.width.offset(xxx);
}];
```

**Comment by shevakuilin** [comment]
> [self.addBankCardBtn mas_makeConstraints:^(MASConstraintMaker *make) {
> make.left.offset(38);
> make.right.offset(-38);
> make.top.offset(12);
> make.bottom.offset(-12);
> }];
> 
> ```
> [LJNArchCutter cuttingView:self.addBankCardBtn cuttingDirection: UIRectCornerTopLeft | UIRectCornerBottomRight   cornerRadii:10 borderWidth:0 borderColor:[UIColor clearColor] backgroundColor:kHex(0xF5F5F5)];
> ```
> 
> ![Snip20190820_7](https://user-images.githubusercontent.com/8566923/63310952-2e596300-c32f-11e9-9b14-18248d9cab0d.png)

已修复，请更新至 0.0.6 版本
